services:
  web:
    build: .
    container_name: src
    command: >
      sh -c "cd src
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/src
    ports:
      - "8000:8000"