services:
  web:
    image: python:3.9-slim
    container_name: src
    command: >
      sh -c "cd src
      && python manage.py migrate
      && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/src
    ports:
      - "8000:8000"
    networks:
      - test_cicd_network

networks:
  test_cicd_network:
    driver: bridge