name: Django CI/CD
on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v3
    - name: Install dependencies
      run: |
        pip install flake8
    - name: Test with flake8
      run: |
        cd /home/myproject/test_cicd &&
        python -m flake8 --max-line-length=100
